In [1]:
import numpy as np

1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [8]:
m = np.arange(12).reshape((3,4))
print("Total mean:",m.mean())
print("Mean of the row:",m.mean(axis=1))
print("Mean of the column:",m.mean(axis=0))

('Total mean:', 5.5)
('Mean of the row:', array([ 1.5,  5.5,  9.5]))
('Mean of the column:', array([ 4.,  5.,  6.,  7.]))


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [47]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Outer product method 1:",np.outer(u,v))

outer=np.array([[]])
for i in u:
    row=np.array([[]])
    for j in v:
        outer=np.append(outer,i*j)
outer=outer.reshape((4,4))
print("Outer product method 2:",outer)

outer=u*v.reshape(len(v),1)
print(outer)

('Outer product method 1:', array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]]))
('Outer product method 2:', array([[  2.,   4.,   6.,   8.],
       [  6.,  12.,  18.,  24.],
       [ 10.,  20.,  30.,  40.],
       [ 14.,  28.,  42.,  56.]]))
[[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [58]:
import numpy.random as npr
m=np.arange(0,6,0.1).reshape(6,10)
print(m)

m=m.astype('uint32')
m=m.astype('float64')
r=npr.rand(6,10)%0.4
output=m+r
print(output)

[[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
 [ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
 [ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9]
 [ 3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9]
 [ 4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9]
 [ 5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9]]
[[ 0.14731193  0.1790386   0.10695843  0.04130144  0.01203746  0.17425031
   0.36274579  0.37837359  0.05196682  0.16572685]
 [ 1.29084718  1.05660321  1.03738438  1.12155679  1.15073864  1.06320352
   1.32498252  1.07390682  1.32519478  1.14245747]
 [ 2.15726351  2.10831706  2.17496966  2.01356538  2.15780227  2.05183682
   2.09853908  2.03574274  2.10263437  2.34713994]
 [ 3.18671233  3.35528944  3.19965629  3.04232157  3.05222128  3.09076349
   3.16734213  3.2277595   3.07418289  3.03762277]
 [ 4.29717406  4.18317751  4.18102276  4.30795425  4.19046756  4.05219515
   4.01208247  4.01722495  4.29555388  4.26008672]
 [ 5.13635248  5.07778637  5.11988601  5.03187178  5.109

4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [66]:
from math import pi
a=np.linspace(0,2*pi,100)

print(a[0:100:10])
print(a[::-1])

[ 0.          0.63466518  1.26933037  1.90399555  2.53866073  3.17332591
  3.8079911   4.44265628  5.07732146  5.71198664]
[ 6.28318531  6.21971879  6.15625227  6.09278575  6.02931923  5.96585272
  5.9023862   5.83891968  5.77545316  5.71198664  5.64852012  5.58505361
  5.52158709  5.45812057  5.39465405  5.33118753  5.26772102  5.2042545
  5.14078798  5.07732146  5.01385494  4.95038842  4.88692191  4.82345539
  4.75998887  4.69652235  4.63305583  4.56958931  4.5061228   4.44265628
  4.37918976  4.31572324  4.25225672  4.1887902   4.12532369  4.06185717
  3.99839065  3.93492413  3.87145761  3.8079911   3.74452458  3.68105806
  3.61759154  3.55412502  3.4906585   3.42719199  3.36372547  3.30025895
  3.23679243  3.17332591  3.10985939  3.04639288  2.98292636  2.91945984
  2.85599332  2.7925268   2.72906028  2.66559377  2.60212725  2.53866073
  2.47519421  2.41172769  2.34826118  2.28479466  2.22132814  2.15786162
  2.0943951   2.03092858  1.96746207  1.90399555  1.84052903  1.77706251
  

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)