1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [5]:
import numpy as np
x = np.arange(12).reshape((3,4))

print("Reference matrix : \n",x)
print ("Total mean: ",x.mean())
print ("Mean for each row : ", x.mean(axis=0))
print ("Mean for each column  : ", x.mean(axis=1))

Reference matrix : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Total mean:  5.5
Mean for each row :  [4. 5. 6. 7.]
Mean for each column  :  [1.5 5.5 9.5]


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [6]:
import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Vector u : ", u)
print("Vector v : ", v)
# 1 Using the function `outer` in numpy
print("1. Using the function `outer` in numpy : \n", np.outer(u, v, out=None))

# 2 Using a nested `for` loop or a list comprehension
outerProd = []
for i in u:
    row = []
    for j in v:        
        row.append(i * j)
    outerProd.append(row)
print("2. Using a nested `for` loop or a list comprehension : \n",outerProd)

# 3 Using numpy broadcasting operations
print("3. Using numpy broadcasting operations : \n",np.array(u)[:,np.newaxis]*v)

Vector u :  [1 3 5 7]
Vector v :  [2 4 6 8]
1. Using the function `outer` in numpy : 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
2. Using a nested `for` loop or a list comprehension : 
 [[2, 4, 6, 8], [6, 12, 18, 24], [10, 20, 30, 40], [14, 28, 42, 56]]
3. Using numpy broadcasting operations : 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [9]:
x= np.linspace(0, 5.9, 60).reshape((10,6))
print("Ref: \n",x)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if x[i,j]%1 < 0.4:
                x[i,j]=0
        else:
            x[i,j]=x[i,j]
print("Betited: \n",x)

Ref: 
 [[0.  0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5 1.6 1.7]
 [1.8 1.9 2.  2.1 2.2 2.3]
 [2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5]
 [3.6 3.7 3.8 3.9 4.  4.1]
 [4.2 4.3 4.4 4.5 4.6 4.7]
 [4.8 4.9 5.  5.1 5.2 5.3]
 [5.4 5.5 5.6 5.7 5.8 5.9]]
Betited: 
 [[0.  0.  0.  0.  0.4 0.5]
 [0.6 0.7 0.8 0.9 0.  0. ]
 [0.  0.  1.4 1.5 1.6 1.7]
 [1.8 1.9 0.  0.  0.  0. ]
 [2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5]
 [3.6 3.7 3.8 3.9 0.  0. ]
 [0.  0.  4.4 4.5 4.6 4.7]
 [4.8 4.9 0.  0.  0.  0. ]
 [5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [13]:
x = np.linspace(0,2 * np.pi, 100)
# Reference Matrix:
print("Reference Matrix: \n", x,"\n")

# Extract every 10th element using the slice notation
print ("Extract every 10th element \n", x[::10],"\n")

# Reverse the array using the slice notation
print ("Reverse the array \n", x[::-1], "\n")

#Extract elements where the absolute difference between the sin and cos functions evaluated for that element is  <0.1
print ("Extract elements where the absolute difference between the sin and cos functions evaluated for that element is  <0.1: \n")
y=[]
for i in range(x.shape[0]):
    if abs(np.sin(x[i])-np.cos(x[i])) < 0.1:
                y.append(x[i])
print(y)

Reference Matrix: 
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [20]:
matr=np.arange(1, 11, 1)
mult_table=matr*matr.reshape(10, 1)
print ("10 by 10 multiplication table : \n", mult_table, " \n")
print("The trace the matrix : \n", mult_table.trace(), " \n")
print("Extract the anti-diagonal matrix  \n", (mult_table).diagonal()," \n")
print("Extract the diagonal offset by 1 upwards \n", np.diagonal(mult_table,1)," \n")

10 by 10 multiplication table : 
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]  

The trace the matrix : 
 385  

Extract the anti-diagonal matrix  
 [  1   4   9  16  25  36  49  64  81 100]  

Extract the diagonal offset by 1 upwards 
 [ 2  6 12 20 30 42 56 72 90]  



6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [36]:
miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
distance = np.abs(miles-miles[:,np.newaxis])
print("Build a 2D grid of distances among each city along Route 66 : \n",distance,"\n")
print("Convert the distances in km : \n", distance*1.609344)

Build a 2D grid of distances among each city along Route 66 : 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 

Convert the distances in km : 
 [[   0.        318.650112  487.631232 1184.477184 1401.738624 1890.9792
  2373.7824   2484.827136 3078.675072 3939.674112]
 [ 318.650112    0.        168.98112   865.827072 1083.088512 1572.329088
  2055.132288 2166.177024 2760.02496  3621.024   ]
 [ 487.631232  168.98112     0.        696.845952  914.107392 1403.347968
  1886.151168 1997.195904 2591.04384  3452.04288 

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [58]:
def PrimeNumbers(n):
    prime = np.ones((n,), dtype=bool)
    prime[:2] = 0
    N_max = int(np.sqrt(len(prime)))
    for j in range(2, N_max):
        prime[2*j::j] = False
    print("Prime numbers sieve: \n ",np.nonzero(prime))

def SieveOfEratosthenes(n):
    prime = [True for i in range(n + 1)]
    p = 2
    while (p * p <= n):
         
        # If prime[p] is not changed, then it is a prime
        if (prime[p] == True):
             
            # Update all multiples of p
            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1
    prime[0]= False
    prime[1]= False
    print("Sieve Of Eratosthenes: \n ")
    for p in range(n + 1):
        if prime[p]:
            print (p)
            
PrimeNumbers(100)
SieveOfEratosthenes(100)

             

Prime numbers sieve: 
  (array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64),)
Sieve Of Eratosthenes: 
 
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
