1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [11]:
import numpy as np

In [12]:

m = np.arange(12).reshape((3,4))
print("m", m)

print("mean m ",np.mean(m))
print("mean each row of m ", np.mean(m[0,:]),np.mean(m[1,:]),np.mean(m[2,:]))
print("mean each column  of m ", np.mean(m[:,0]),np.mean(m[:,1]),np.mean(m[:,2]),np.mean(m[:,3]))


m [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean m  5.5
mean each row of m  1.5 5.5 9.5
mean each column  of m  4.0 5.0 6.0 7.0


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [13]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("U:\n",u)
print("V:\n",v)


U:
 [1 3 5 7]
V:
 [2 4 6 8]


In [14]:

print("product using outer \n", np.outer(u,v))


product using outer 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [15]:
uv=[]
for i in range(4):
  uv.append(u[i]*v[i])
print("product using for loop \n", uv)

  

product using for loop 
 [2, 12, 30, 56]


In [16]:
print("Using numpy broadcasting operations", u*v)

Using numpy broadcasting operations [ 2 12 30 56]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [17]:
c=0
m=np.ones((6,10))

for i in range (6):
   for j in range (10):
     m[i,j]=c
     c+=0.1
print("M:\n", m)

m[:,:4]=0
print("M:\n", m)



M:
 [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]
M:
 [[0.  0.  0.  0.  0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.  0.  0.  1.4 1.5 1.6 1.7 1.8 1.9]
 [0.  0.  0.  0.  2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5 3.6 3.7 3.8 3.9]
 [0.  0.  0.  0.  4.4 4.5 4.6 4.7 4.8 4.9]
 [0.  0.  0.  0.  5.4 5.5 5.6 5.7 5.8 5.9]]



4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [18]:
import math as m
l=np.linspace(0,2*m.pi,100)
print("Full list:\n",l)
print("-"*100)
print("All the 10th elements:\n",l[0::10])  
print("-"*100)
print("reversed list", l[::-1])
print("-"*100)
print("elements where the absolute difference between the sin and cos functions evaluated for that element is  <0.1 \n")
for i in range (100):
  if(abs(m.sin(l[i])-m.cos(l[i]))<0.1):
    print(l[i])


Full list:
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [19]:
mult_table=np.eye(10,10)
for i in range(0,10):
  for j in range (0,10):
    mult_table[i,j]=((i+1)*(j+1))

print("Trance ",mult_table.trace())
print("The anti-diagonal matrix ",np.fliplr(mult_table).diagonal())
print("The diagonal offset by 1 upwards",np.diagonal(mult_table,1))



Trance  385.0
The anti-diagonal matrix  [10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
The diagonal offset by 1 upwards [ 2.  6. 12. 20. 30. 42. 56. 72. 90.]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [25]:
 positions=[0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]
 dist=np.eye(len(positions))
 for i in range(len(positions)):
   for j in range(len(positions)):
     dist[i,j]=abs(positions[i]-positions[j])

print(dist)
print("\ndistances in km:\n")  
print(dist*0.621371)


[[   0.  198.  303.  736.  871. 1175. 1475. 1544. 1913. 2448.]
 [ 198.    0.  105.  538.  673.  977. 1277. 1346. 1715. 2250.]
 [ 303.  105.    0.  433.  568.  872. 1172. 1241. 1610. 2145.]
 [ 736.  538.  433.    0.  135.  439.  739.  808. 1177. 1712.]
 [ 871.  673.  568.  135.    0.  304.  604.  673. 1042. 1577.]
 [1175.  977.  872.  439.  304.    0.  300.  369.  738. 1273.]
 [1475. 1277. 1172.  739.  604.  300.    0.   69.  438.  973.]
 [1544. 1346. 1241.  808.  673.  369.   69.    0.  369.  904.]
 [1913. 1715. 1610. 1177. 1042.  738.  438.  369.    0.  535.]
 [2448. 2250. 2145. 1712. 1577. 1273.  973.  904.  535.    0.]]

distances in km:

[[   0.        123.031458  188.275413  457.329056  541.214141  730.110925
   916.522225  959.396824 1188.682723 1521.116208]
 [ 123.031458    0.         65.243955  334.297598  418.182683  607.079467
   793.490767  836.365366 1065.651265 1398.08475 ]
 [ 188.275413   65.243955    0.        269.053643  352.938728  541.835512
   728.246812  771.121411 

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [38]:
def Sieve(n):
	pr = [True for i in range(n + 1)]
	p = 2
	while (p * p <= n):
		if (pr[p] == True):			
			for i in range(p ** 2, n + 1, p):
				pr[i] = False
		p += 1
	pr[0]= False
	pr[1]= False

	for p in range(n + 1):
		if pr[p]:
			print( p) 

n = 90
%timeit Sieve(n)


Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
2
3
5
7
11
13
17
