1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [7]:
import numpy as np

m = np.arange(12).reshape((3,4))

print('The matrix m: \n',m)
print("Total mean:\n", np.mean(m))
print("Mean for each column:\n", np.mean(m, axis=0))   
print("Mean for each row:\n", np.mean(m, axis=1))


The matrix m: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Total mean:
 5.5
Mean for each column:
 [4. 5. 6. 7.]
Mean for each row:
 [1.5 5.5 9.5]


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [10]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

uv1 = np.outer(u, v)
print("Outer function with numpy:\n", uv1)

uv2 = np.array([i*j for i in u for j in v]).reshape((4,4))
print("\nOuter function with List comprehension :\n", uv2)

u_temp = np.tile(u,(4,1)).T
uv3 = u_temp * v
print("\nOuter function with Broadcasting operations:\n", uv3)

Outer function with numpy:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Outer function with List comprehension :
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Outer function with Broadcasting operations:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [15]:
m = np.arange(0, 6, 0.1).reshape((6, 10))
print('The matrix m\n',m)

m[m % 1 < 0.4] = 0 #Sets all entries with a decimal part < 0.4 to zero
print ("\nModified matrix m: \n", m)



The matrix m
 [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]

Modified matrix m: 
 [[0.  0.  0.  0.  0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.  0.  0.  1.4 1.5 1.6 1.7 1.8 1.9]
 [0.  0.  0.  0.  2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5 3.6 3.7 3.8 3.9]
 [0.  0.  0.  0.  4.4 4.5 4.6 4.7 4.8 4.9]
 [0.  0.  0.  0.  5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [21]:
from math import pi

m = np.linspace(0, 2*pi, 100)
print('Array of 100 numbers between 0 and 2π\n',m)

n = m[::10]
print('\nExtracted every 10th element\n',n)

p = m[::-1]
print('\nReverse the array\n',p)

#  
q = m[np.abs(np.sin(m) - np.cos(m)) < 0.1]
print('\nExtracted elements for absolute difference of sin and cos functions evaluated for that element is <0.1\n',q)

Array of 100 numbers between 0 and 2π
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [28]:
u = np.arange(1, 11)
v = np.array([u]).T

m = u * v
print('Matrix with 10 by 10 multiplication table:\n', m)

trace = sum(np.diag(m))
print('\nTrace of the matrix m:', trace)

anti_diag = m[:, ::-1].diagonal(0)
print('\nAnti-diagonal matrix:', anti_diag)

diag = m.diagonal(1)
print('\nDiagonal offset by 1 upwards:', diag)

Matrix with 10 by 10 multiplication table:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

Trace of the matrix m: 385

Anti-diagonal matrix: [10 18 24 28 30 30 28 24 18 10]

Diagonal offset by 1 upwards: [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [30]:
u = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
v = np.array([u]).T

dist = np.abs(u-v)
print('2D grid of distances among each city along Route 66\n', dist)

dist_km = dist * 1.6 # coversion from miles to km
print('\nDistances in km', dist_km)

2D grid of distances among each city along Route 66
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]

Distances in km [[   0.   316.8  484.8 1177.6 1393.6 1880.  2360.  2470.4 3060.8 3916.8]
 [ 316.8    0.   168.   860.8 1076.8 1563.2 2043.2 2153.6 2744.  3600. ]
 [ 484.8  168.     0.   692.8  908.8 1395.2 1875.2 1985.6 2576.  3432. ]
 [1177.6  860.8  692.8    0.   216.   702.4 1182.4 1292.8 1883.2 2739.2]
 [1393.6 1076.8  908.8  216.     0.   486.4  966.4 1076.8 1667.2 2523.2]
 [1880.  1563.2 1395.2  702.4  486

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [36]:
import time

def prime_num(num):
    prime = []
    for n in range(0, num+1):
        if n > 1:
            for i in range(2,n):
                if (n % i) == 0:
                    break
            else:
                prime.append(n)
    return prime
                
primes=prime_num(99)
print('Prime numbers: ',primes)

%timeit prime_num(99)
%timeit prime_num(210)
%timeit prime_num(350) # Not optimised since time is not linear in the number of N


# Using sieve of Eratosthenes
def prime_eratosthenes(n):
    primes = []
    prime = [True for i in range(n + 1)]
    p = 2
    while (p * p <= n):
        if (prime[p] == True):
            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1
    prime[0]= False
    prime[1]= False
    for p in range(n + 1):
        if prime[p]:
            primes.append(p)
    return primes
            
p = prime_eratosthenes(99)
print('\nPrime numbers with the sieve of Eratosthenes:\n',p)

Prime numbers:  [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
94.7 µs ± 780 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
319 µs ± 2.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
548 µs ± 3.66 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Prime numbers with the sieve of Eratosthenes:
 [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
