1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
m = np.arange(12).reshape((3,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
total_mea = np.mean(m)
row1 = np.mean(m[0])
row2 = np.mean(m[0])
row3 = np.mean(m[0])

# col1 = np.mean(m[:][3])

col1 = np.mean(m[:,0])
col2 = np.mean(m[:,1])
col3 = np.mean(m[:,2])
col4 = np.mean(m[:,3])



2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [4]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#1
num_out = np.outer(u,v)
# print(num_out)
#2
mul = []
for element_u in u:
    mul2 = []
    for element_v in v:
        mul2.append(element_u*element_v)
    mul.append(mul2)
mul = np.array(mul)
# print(mul)
#3 

list_comp = np.array([items_u*items_v for items_u in u for items_v in v]).reshape(4,4)
# print(list_comp)
#4 broadcasting opearations

u*v.reshape(4,1)


array([[ 2,  6, 10, 14],
       [ 4, 12, 20, 28],
       [ 6, 18, 30, 42],
       [ 8, 24, 40, 56]])

3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [5]:
# print(np.linspace(start = 0, stop = 6, num=60, endpoint=True, retstep=True, dtype=None, axis=0,step = 0.1).reshape(10,6))
np.linspace(start = 0, stop = 6, num=60, endpoint=True, retstep=False, dtype=None, axis=0)

array([0.        , 0.10169492, 0.20338983, 0.30508475, 0.40677966,
       0.50847458, 0.61016949, 0.71186441, 0.81355932, 0.91525424,
       1.01694915, 1.11864407, 1.22033898, 1.3220339 , 1.42372881,
       1.52542373, 1.62711864, 1.72881356, 1.83050847, 1.93220339,
       2.03389831, 2.13559322, 2.23728814, 2.33898305, 2.44067797,
       2.54237288, 2.6440678 , 2.74576271, 2.84745763, 2.94915254,
       3.05084746, 3.15254237, 3.25423729, 3.3559322 , 3.45762712,
       3.55932203, 3.66101695, 3.76271186, 3.86440678, 3.96610169,
       4.06779661, 4.16949153, 4.27118644, 4.37288136, 4.47457627,
       4.57627119, 4.6779661 , 4.77966102, 4.88135593, 4.98305085,
       5.08474576, 5.18644068, 5.28813559, 5.38983051, 5.49152542,
       5.59322034, 5.69491525, 5.79661017, 5.89830508, 6.        ])

4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [8]:
arr1 = np.linspace(start = 0, stop = np.pi*2, num=100, endpoint=True, retstep=False, dtype=None, axis=0)
arr_reversed = arr1[::-1]
arr_10th = arr1[::10]
arr_sin_cos = np.where(np.absolute(np.sin(arr1)-np.cos(arr1))<0.1,arr1,None)
#np.delete(arr_sin_cos,None)
arr_sin_cos = set(arr_sin_cos)
arr_sin_cos.remove(None)
arr_sin_cos

{0.7615982190520711, 0.8250647373064104, 3.8714576135146945, 3.934924131769034}

In [17]:
arr1

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [71]:
ten_by_ten = np.arange(1,11)
ten_by_ten = ten_by_ten*ten_by_ten[:,None]
trace = np.trace(ten_by_ten)
# trace = sum(np.arange(0,11)*np.arange(0,11))
flipped = np.fliplr(ten_by_ten)
anti_diag = np.diag(flipped)

one_upwards = [ten_by_ten[i][i-1] for i in range(1,len(ten_by_ten))]

6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [76]:
cities = [ "Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo","Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
distances = [0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]
grid = np.tile(distances,len(distances))
grid

array([   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,
        198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,
        303,  736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,
        736,  871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,
        871, 1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,  871,
       1175, 1475, 1544, 1913, 2448,    0,  198,  303,  736,  871, 1175,
       1475, 1544, 1913, 2448,    0,  198,  303,  736,  871, 1175, 1475,
       1544, 1913, 2448,    0,  198,  303,  736,  871, 1175, 1475, 1544,
       1913, 2448,    0,  198,  303,  736,  871, 1175, 1475, 1544, 1913,
       2448])

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [123]:
def prime_computer(N):
    
    tmp = np.ones(N, dtype=bool)
    tmp[0] = tmp[1] = False
    for i in range(2, N):
        # We could use a lower upper bound for this loop, but I don't want to bother with
        # getting the rounding right on the sqrt handling.
        if tmp[i]:
            tmp[i*i::i] = False
    return np.flatnonzero(tmp)
        

In [2]:
import timeit
timeit.timeit.prime_computer(99)
#prime_computer(99)


AttributeError: 'function' object has no attribute 'prime_computer'

In [ ]:
#time it and sin cos plot missing