1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np # import naming convention

In [2]:
m = np.arange(12).reshape((3,4))
print("total mean:",m.mean())
print("mean for column",m.mean(axis=0))
print("mean for row",m.mean(axis=1))
    

total mean: 5.5
mean for column [4. 5. 6. 7.]
mean for row [1.5 5.5 9.5]


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [3]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("outer: \n",np.outer(u,v))
a=np.zeros((4,4))
for i in range(0,len(u)):
    for j in range(0,len(v)):
        a[i,j]=u[i]*v[j]
        
print("nested for: \n",a)
k=np.tile(u,(1,1)).T
print("broadcasting: \n",(k*v))

outer: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
nested for: 
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
broadcasting: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [4]:
matrix = np.fromfunction(lambda i, j: i*1 + j*(1/10), (6, 10))
print(matrix)

for i in range(0,matrix.shape[0]):
    for j in range(0,matrix.shape[1]):
        if matrix[i,j]<0.4:
            matrix[i,j]=0
print(matrix)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]
[[0.  0.  0.  0.  0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [5]:
from math import pi,sin,cos

array = np.linspace(0, 2*pi,100)
print("total: \n",array)

print("step 10: \n", array[::10])
print("reverse: \n", array[::-1])
mask=[]
for i in range(0,len(array)):
    mask.append(abs(sin(array[i])-cos(array[i]))< 0.1)
filter_array = array[mask]
print ("filter: \n", filter_array)


total: 
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [33]:
multiplication = np.fromfunction(lambda i, j: (i+1)*(j+1), (10, 10))
print("matrix: \n",multiplication)
print("trace: ",np.sum(np.diag(multiplication)))
print("anti-diagonal: ",np.diag(np.fliplr(multiplication)))
print("diagonal offset by 1 upwards: ",np.diag(multiplication,1))

matrix: 
 [[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
trace:  385.0
anti-diagonal:  [10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
diagonal offset by 1 upwards:  [ 2.  6. 12. 20. 30. 42. 56. 72. 90.]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [75]:
distance = np.array([0,198,303,736,871,1175,1475,1544,1913,2248])
dist = np.tile(distance,(1,1)).T
print("In miles: \n     CH    Sp  Sai  Tul  OKC  Ama  San  Alb Flag  LA \n",abs(distance - dist))
print("In km: \n",np.round(abs(distance - dist)/0.621))

In miles: 
     CH    Sp  Sai  Tul  OKC  Ama  San  Alb Flag  LA 
 [[   0  198  303  736  871 1175 1475 1544 1913 2248]
 [ 198    0  105  538  673  977 1277 1346 1715 2050]
 [ 303  105    0  433  568  872 1172 1241 1610 1945]
 [ 736  538  433    0  135  439  739  808 1177 1512]
 [ 871  673  568  135    0  304  604  673 1042 1377]
 [1175  977  872  439  304    0  300  369  738 1073]
 [1475 1277 1172  739  604  300    0   69  438  773]
 [1544 1346 1241  808  673  369   69    0  369  704]
 [1913 1715 1610 1177 1042  738  438  369    0  335]
 [2248 2050 1945 1512 1377 1073  773  704  335    0]]
In km: 
 [[   0.  319.  488. 1185. 1403. 1892. 2375. 2486. 3081. 3620.]
 [ 319.    0.  169.  866. 1084. 1573. 2056. 2167. 2762. 3301.]
 [ 488.  169.    0.  697.  915. 1404. 1887. 1998. 2593. 3132.]
 [1185.  866.  697.    0.  217.  707. 1190. 1301. 1895. 2435.]
 [1403. 1084.  915.  217.    0.  490.  973. 1084. 1678. 2217.]
 [1892. 1573. 1404.  707.  490.    0.  483.  594. 1188. 1728.]
 [2375. 2056. 18

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)
  
  

In [273]:
def isprime(k):
    div = 2
    if k==1 or k==0:
        return False
    elif k == 3 or k==2:
        return True
    else:
        while div!=k:        
            if k%div==0:
                return False
            else:
                div+=1
        return True
                            
N=100
numbers = np.arange(N)
mask=[]
%timeit for i in range(0,len(numbers)):mask.append(isprime(numbers[i]))
print(numbers[mask[0:N]])

#the timeit is exponential with refer to N

627 µs ± 2.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [274]:
def erathostene(limit):
    a = [True]*limit
    a[0] = a[1] = False 
    i=2
    while i<limit:
        if a[i]==True:
            k=i+i
            while k < limit:
                a[k]=False
                k=k+i
        i+=1
    return a
%timeit mask = erathostene(N)
print(numbers[mask[0:N]])

22.5 µs ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
