In [2]:
import pandas as pd
import numpy as np

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [44]:
l=[i for i in range(10)]
m = np.arange(1.0,26.0).reshape((5,5))

with open("data_int.txt", 'w') as file:
    file.write(' '.join(map(str, l)) + '\n')
    
with open("data_float.txt", 'w') as file1:
    file1.write(str(m)  + '\n')

with open("data_float.txt", 'r') as file2:
    with open("data_float.csv", 'w') as file3:
        for l in file2:
            file3.write(",".join(re.findall('\d+', l)) + '\n')

#type because of Windows
print("Content of the file data_int.txt:")
!type "data_int.txt" 
print('\n')

print("Content of the file data_float.txt:")
!type "data_float.txt"
print('\n')

print("Content of the file data_float.csv:")
!type "data_float.csv"

Content of the file data_int.txt:
0 1 2 3 4 5 6 7 8 9


Content of the file data_float.txt:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


Content of the file data_float.csv:
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15
16,17,18,19,20
21,22,23,24,25


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [47]:
import json

data = json.load(open('user_data.json'))
data_filtred = [x for x in data if x['CreditCardType'] == 'American Express']
data_new = pd.DataFrame(data_filtred)

data_new.to_csv('user_data.csv', index = None)
data_new

ID               JobTitle                       EmailAddress  \
0     2    Investment  Advisor       Clint_Thorpe5003@bulaffy.com   
1    12         Retail Trainee   Phillip_Carpenter9505@famism.biz   
2    28        Project Manager        Russel_Graves1378@extex.org   
3    39            Stockbroker       Leanne_Newton1268@typill.biz   
4    57         Budget Analyst          Tony_Giles1960@iatim.tech   
5    62           CNC Operator        Owen_Allcott5125@bauros.biz   
6    68        Project Manager           Liam_Lynn3280@kideod.biz   
7    74                Dentist      Regina_Woodcock5820@yahoo.com   
8    81          HR Specialist       Carter_Wallace9614@atink.com   
9    92    Staffing Consultant           Maia_Stark2797@jiman.org   
10   97            Stockbroker          Ciara_Lomax982@bauros.biz   
11  116    Staffing Consultant      Isabel_Ellwood1475@fuliss.net   
12  148           CNC Operator  Abdul_Townend2202@infotech44.tech   
13  150             Fabricator        Caleb_Poulton1735@atink.com   
14  151     Restaurant Manager         Ronald_Lewis6777@deavo.com   
15  154                Bellman        Faith_Seymour3829@twace.org   
16  169        Assistant Buyer      Anthony_Hancock9083@qater.org   
17  176  Healthcare Specialist    Isabella_Willson5478@nanoff.biz   
18  182             Pharmacist     Stephanie_Darcy3298@bauros.biz   
19  199    Investment  Advisor         Ryan_Kennedy5565@corti.com   

    FirstNameLastName           CreditCard    CreditCardType  
0        Clint Thorpe  7083-8766-0251-2345  American Express  
1   Phillip Carpenter  3657-0088-0820-5247  American Express  
2       Russel Graves  6718-4818-8011-6024  American Express  
3       Leanne Newton  5438-0816-4166-4847  American Express  
4          Tony Giles  8130-3425-7573-7745  American Express  
5        Owen Allcott  4156-0107-7210-2630  American Express  
6           Liam Lynn  7152-3247-6053-2233  American Express  
7     Regina Woodcock  0208-1753-3870-8002  American Express  
8      Carter Wallace  4256-7201-6717-4322  American Express  
9          Maia Stark  3851-1403-1734-6321  American Express  
10        Ciara Lomax  3702-3440-2472-5424  American Express  
11     Isabel Ellwood  3738-0882-0066-6683  American Express  
12      Abdul Townend  4224-1226-3557-3448  American Express  
13      Caleb Poulton  8203-6875-5225-0341  American Express  
14       Ronald Lewis  7212-0155-5014-8471  American Express  
15      Faith Seymour  4170-5186-6887-6558  American Express  
16    Anthony Hancock  0832-3357-6010-6550  American Express  
17   Isabella Willson  5177-4868-4623-0384  American Express  
18    Stephanie Darcy  0264-4020-5106-5576  American Express  
19       Ryan Kennedy  3166-6287-6242-7207  American Express

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [57]:
#explore and print the DataFrame
import json

data = pd.read_csv("mushrooms_categorized.csv")
data


class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [72]:
#calculate, using groupby(), the average value of each feature, separately for each class

data_grouped = data.groupby('class')
data_grouped.mean()



cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

In [75]:
#save the file in a JSON format.

data.to_json('mushrooms_categorized.json', orient = 'columns')

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [69]:
n = 6

with open('credit_card.dat','rb') as file:
    for line in file:
        num_card = [chr(int(line[i:i + n], 2)) for i in range(0, len(line)-n, n)]
        print(''.join(str(i) for i in num_card))
        

7648 5673 3775 2271
3257 8247 3354 2266
2722 0001 4011 6652
0661 3063 3742 3150
0432 1608 1462 4742
5827 2027 8785 7303
5774 8528 2087 1117
8140 1210 6352 2845
5764 1133 7301 7100
6456 1737 4126 6726
1228 8631 7382 0000
7051 0160 5374 3166
0618 3587 1630 6376
1545 5454 7444 5636
6735 3116 3202 6834
7287 5011 1547 8413
7033 2607 3328 4200
2568 5244 1874 5024
1684 2253 7570 7118
0672 2576 0575 6631
6332 8353 8787 1340
1813 3361 1175 4211
2477 6450 8840 2368
5512 3505 2563 1326
3083 7882 0621 0025
4521 5148 8045 0334
7563 3654 8713 5787
8324 2664 0476 5561
0565 2504 7168 3510
5107 5507 1767 0738
2462 1821 2448 1443
2788 0638 6861 6554
5851 5873 5474 0547
0670 1004 4013 2655
5874 5506 3048 0806
2805 5401 8462 1260
5083 8406 6310 1862
1076 1445 3013 2266
8440 4804 4844 5277
4758 6141 0686 1387
7586 0675 0315 2568
2544 1258 7432 5165
3474 5023 4434 5626
1410 0270 0434 5086
7315 4446 1104 4215
0224 7742 8300 0266
0170 2700 3145 0640
2006 2437 8054 1600
8142 4055 1776 0026
3026 7380 1241 1084


5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3