In [18]:
import pandas as pd
import numpy as np
import csv

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [19]:
out_file_int = "data/data_int.txt"
list_int = [1,2,3,4,5,6]
with open(out_file_int, 'a') as outfile:
    outfile.write(str(list_int)) 
    
#!cat data/data_int.txt  --> This is the command cat for unix users
!type C:\Users\frego\Desktop\HLP\data\"data_int.txt" 

    
out_file_float = "data/data_float.txt"
#I create a random matrix of float from 0.5 to 10
matrix_float = np.random.uniform(low=0.5, high=10, size=25).reshape((5,5))
with open(out_file_float, 'a') as outfile:
    outfile.write(str(matrix_float)) 

!type C:\Users\frego\Desktop\HLP\data\"data_float.txt" 
    
read_file = pd.read_csv(r'C:\Users\frego\Desktop\HLP\data\data_float.txt')
read_file.to_csv(r'C:\Users\frego\Desktop\HLP\data\data_float.csv', index=None)

[1, 2, 3, 4, 5, 6]
[[8.45674393 5.54040473 1.85077564 1.44000717 1.90645973]
 [5.4760438  5.71150991 1.98387462 8.43759282 9.29100694]
 [3.55719421 2.11409793 7.06555081 4.87049764 9.12231666]
 [6.92523009 9.94001612 4.88814594 8.05067306 4.26573558]
 [1.29596099 3.56935531 5.10878073 4.64708179 8.90157202]]


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [65]:
import urllib.request
import json 
import requests

url = 'https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json'

response = requests.get(url)
response.raise_for_status() 

#I need to handle the encoding format
if (
    response.status_code != 204 and
    response.headers["content-type"].strip().startswith("application/json")
):
    try:
        data = response.json()
    except ValueError:
        print(ValueError)
        

filtered_data = [x for x in data if (x['CreditCardType'] == 'American Express')]

read_file = pd.DataFrame(filtered_data)
read_file.to_csv (r'C:\Users\frego\Desktop\HLP\data\filtered_CSV.csv', index=None)

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [119]:
#url_csv = "https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv"

df = pd.read_csv("data/mushrooms_categorized.csv")

gr_class = df.groupby('class').mean()
read_file.to_json (r'C:\Users\frego\Desktop\HLP\data\Average_feature_JSON.json')

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3