In [13]:
import pandas as pd
import numpy as np

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [18]:
import csv

n = [x for x in range(100)]
print(n)

txt_f = open('data_int.txt', 'w')

with open('data_int.txt', 'w') as f:
    f.write(str(n))

#!cat data_int.txt
!type data_int.txt # type is equivalent of cat in windows

matrix = np.array(range(25)).reshape(5,5)

txt_f = open('data_float.txt', 'w')

with open('data_float.txt', 'w') as f:
    f.write(str(matrix))

#!cat data_float.txt
!type data_float.txt

with open('data_float.txt', 'r') as txt_f:
    f_line = (line.strip() for line in txt_f)
    lines = (line.split(",") for line in f_line if line)
    with open('data_float.csv', 'w') as csv_f:
        writer = csv.writer(csv_f)
        writer.writerows(lines)

#!cat data_float.csv
!type data_float.csv

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]



data_int.txt


The system cannot find the file specified.
Error occurred while processing: #.
The system cannot find the file specified.
Error occurred while processing: type.
The system cannot find the file specified.
Error occurred while processing: is.
The system cannot find the file specified.
Error occurred while processing: equivalent.
The system cannot find the file specified.
Error occurred while processing: of.
The system cannot find the file specified.
Error occurred while processing: cat.
The system cannot find the file specified.
Error occurred while processing: in.
The system cannot find the file specified.
Error occurred while processing: windows.


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]

[ 5  6  7  8  9]

[10 11 12 13 14]

[15 16 17 18 19]

[20 21 22 23 24]]



2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [21]:
import json

data = json.load(open('user_data.json'))
filtered_data = [x for x in data if x['CreditCardType'] == 'American Express']
    
df=pd.DataFrame(filtered_data) 
df.to_csv('AmericanExpress.csv')
df

!type AmericanExpress.csv

,CreditCard,CreditCardType,EmailAddress,FirstNameLastName,ID,JobTitle
0,7083-8766-0251-2345,American Express,Clint_Thorpe5003@bulaffy.com,Clint Thorpe,2,Investment  Advisor
1,3657-0088-0820-5247,American Express,Phillip_Carpenter9505@famism.biz,Phillip Carpenter,12,Retail Trainee
2,6718-4818-8011-6024,American Express,Russel_Graves1378@extex.org,Russel Graves,28,Project Manager
3,5438-0816-4166-4847,American Express,Leanne_Newton1268@typill.biz,Leanne Newton,39,Stockbroker
4,8130-3425-7573-7745,American Express,Tony_Giles1960@iatim.tech,Tony Giles,57,Budget Analyst
5,4156-0107-7210-2630,American Express,Owen_Allcott5125@bauros.biz,Owen Allcott,62,CNC Operator
6,7152-3247-6053-2233,American Express,Liam_Lynn3280@kideod.biz,Liam Lynn,68,Project Manager
7,0208-1753-3870-8002,American Express,Regina_Woodcock5820@yahoo.com,Regina Woodcock,74,Dentist
8,4256-7201-6717-4322,American Express,Carter_Wallace9614@atink.com,Carter Wallace,81,HR Specialist
9,3851-1403-1734-6321,American Express,Maia

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [23]:
file_name = 'mushrooms_categorized.csv'
data = pd.read_csv(file_name)
data.head()

avg_values = data.groupby('class').mean()
avg_values

avg_values.to_json('mushrooms_solved.json', orient = 'index')

!type mushrooms_solved.json 

{"0":{"cap-shape":3.2661596958,"cap-surface":1.6159695817,"cap-color":4.5817490494,"bruises":0.6539923954,"odor":4.3346007605,"gill-attachment":0.9543726236,"gill-spacing":0.2851711027,"gill-size":0.0684410646,"gill-color":6.6226235741,"stalk-shape":0.6159695817,"stalk-root":1.4980988593,"stalk-surface-above-ring":1.7756653992,"stalk-surface-below-ring":1.7984790875,"stalk-color-above-ring":6.0988593156,"stalk-color-below-ring":6.0646387833,"veil-type":0.0,"veil-color":1.9315589354,"ring-number":1.1254752852,"ring-type":3.0076045627,"spore-print-color":3.2015209125,"population":3.283269962,"habitat":1.1482889734},"1":{"cap-shape":3.4361593463,"cap-surface":2.0551583248,"cap-color":4.4218590398,"bruises":0.1593462717,"odor":3.9407558733,"gill-attachment":0.9954034729,"gill-spacing":0.0286006129,"gill-size":0.5679264556,"gill-color":2.8636363636,"stalk-shape":0.5148110317,"stalk-root":0.6925434116,"stalk-surface-above-ring":1.3595505618,"stalk-surface-below-ring":1.3942798774,"stalk-colo

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [25]:
def binary_to_str(block):
    num1 = chr(int(block[0:6], 2))
    num2 = chr(int(block[6:12], 2))
    num3 = chr(int(block[12:18], 2))
    num4 = chr(int(block[18:24], 2))
    return num1 + num2 + num3 + num4
    

with open('credit_card.dat', 'r') as f:
    data = f.read()
    
    lines = data.split('\n')[:-2]
    for line in lines:
        block1 = line[0:24]
        block2 = line[30:54]
        block3 = line[60:84]
        block4 = line[90:114]
        
        card_number = binary_to_str(block1) + ' ' + binary_to_str(block2) + ' ' + binary_to_str(block3) + ' ' + binary_to_str(block4)
        print(card_number)

7648 5673 3775 2271
3257 8247 3354 2266
2722 0001 4011 6652
0661 3063 3742 3150
0432 1608 1462 4742
5827 2027 8785 7303
5774 8528 2087 1117
8140 1210 6352 2845
5764 1133 7301 7100
6456 1737 4126 6726
1228 8631 7382 0000
7051 0160 5374 3166
0618 3587 1630 6376
1545 5454 7444 5636
6735 3116 3202 6834
7287 5011 1547 8413
7033 2607 3328 4200
2568 5244 1874 5024
1684 2253 7570 7118
0672 2576 0575 6631
6332 8353 8787 1340
1813 3361 1175 4211
2477 6450 8840 2368
5512 3505 2563 1326
3083 7882 0621 0025
4521 5148 8045 0334
7563 3654 8713 5787
8324 2664 0476 5561
0565 2504 7168 3510
5107 5507 1767 0738
2462 1821 2448 1443
2788 0638 6861 6554
5851 5873 5474 0547
0670 1004 4013 2655
5874 5506 3048 0806
2805 5401 8462 1260
5083 8406 6310 1862
1076 1445 3013 2266
8440 4804 4844 5277
4758 6141 0686 1387
7586 0675 0315 2568
2544 1258 7432 5165
3474 5023 4434 5626
1410 0270 0434 5086
7315 4446 1104 4215
0224 7742 8300 0266
0170 2700 3145 0640
2006 2437 8054 1600
8142 4055 1776 0026
3026 7380 1241 1084


5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3