In [1]:
import pandas as pd
import numpy as np

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [93]:
import csv

l=np.random.randint(low=0,high=100,size=5)
out_file_name = "data_int.txt"
with open(out_file_name, 'w') as outfile:
    outfile.write(np.array2string(l)+'\n')
!cat data_int.txt

m=np.random.rand(5,5)
out_file_name = "data_float.txt"
with open(out_file_name, 'w') as outfile:
    outfile.write(np.array2string(m)+'\n')
!cat data_float.txt

out_file_csv = "data_csv.csv"
with open(out_file_name, 'r') as infile:
    with open(out_file_csv, 'w', newline='') as outfile:
        writer = csv.writer(outfile)
        for line in csv.reader(infile, delimiter=' '):
            while ('' in line):
                line.remove('')
            for i,j in zip(line,range(0,len(line))):
                line[j]=i.replace('[','').replace(']','')
            writer.writerow(line)

[42 14 54 21 63]
[[0.31501776 0.81632735 0.67713093 0.99340102 0.33633515]
 [0.20004685 0.06772474 0.00694175 0.8855301  0.83623171]
 [0.01834466 0.82554653 0.64254013 0.09394319 0.08504865]
 [0.91457058 0.6194536  0.07235357 0.06321282 0.31853466]
 [0.26206588 0.50567083 0.11934385 0.92852831 0.94676539]]


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [ ]:
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

In [94]:
import json
data = json.load(open('user_data.json'))

def AmericanExpress(x):
    return x["CreditCardType"]=="American Express"

result=list(filter(AmericanExpress,data))
fieldnames = ['ID', 'JobTitle', 'EmailAddress', 'FirstNameLastName','CreditCard','CreditCardType']
with open('output.csv', 'w',newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(result)

data = pd.read_csv('output.csv')
data

ID               JobTitle                       EmailAddress  \
0     2    Investment  Advisor       Clint_Thorpe5003@bulaffy.com   
1    12         Retail Trainee   Phillip_Carpenter9505@famism.biz   
2    28        Project Manager        Russel_Graves1378@extex.org   
3    39            Stockbroker       Leanne_Newton1268@typill.biz   
4    57         Budget Analyst          Tony_Giles1960@iatim.tech   
5    62           CNC Operator        Owen_Allcott5125@bauros.biz   
6    68        Project Manager           Liam_Lynn3280@kideod.biz   
7    74                Dentist      Regina_Woodcock5820@yahoo.com   
8    81          HR Specialist       Carter_Wallace9614@atink.com   
9    92    Staffing Consultant           Maia_Stark2797@jiman.org   
10   97            Stockbroker          Ciara_Lomax982@bauros.biz   
11  116    Staffing Consultant      Isabel_Ellwood1475@fuliss.net   
12  148           CNC Operator  Abdul_Townend2202@infotech44.tech   
13  150             Fabricator        Caleb_Poulton1735@atink.com   
14  151     Restaurant Manager         Ronald_Lewis6777@deavo.com   
15  154                Bellman        Faith_Seymour3829@twace.org   
16  169        Assistant Buyer      Anthony_Hancock9083@qater.org   
17  176  Healthcare Specialist    Isabella_Willson5478@nanoff.biz   
18  182             Pharmacist     Stephanie_Darcy3298@bauros.biz   
19  199    Investment  Advisor         Ryan_Kennedy5565@corti.com   

    FirstNameLastName           CreditCard    CreditCardType  
0        Clint Thorpe  7083-8766-0251-2345  American Express  
1   Phillip Carpenter  3657-0088-0820-5247  American Express  
2       Russel Graves  6718-4818-8011-6024  American Express  
3       Leanne Newton  5438-0816-4166-4847  American Express  
4          Tony Giles  8130-3425-7573-7745  American Express  
5        Owen Allcott  4156-0107-7210-2630  American Express  
6           Liam Lynn  7152-3247-6053-2233  American Express  
7     Regina Woodcock  0208-1753-3870-8002  American Express  
8      Carter Wallace  4256-7201-6717-4322  American Express  
9          Maia Stark  3851-1403-1734-6321  American Express  
10        Ciara Lomax  3702-3440-2472-5424  American Express  
11     Isabel Ellwood  3738-0882-0066-6683  American Express  
12      Abdul Townend  4224-1226-3557-3448  American Express  
13      Caleb Poulton  8203-6875-5225-0341  American Express  
14       Ronald Lewis  7212-0155-5014-8471  American Express  
15      Faith Seymour  4170-5186-6887-6558  American Express  
16    Anthony Hancock  0832-3357-6010-6550  American Express  
17   Isabella Willson  5177-4868-4623-0384  American Express  
18    Stephanie Darcy  0264-4020-5106-5576  American Express  
19       Ryan Kennedy  3166-6287-6242-7207  American Express

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [ ]:
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

In [105]:
data = pd.read_csv('mushrooms_categorized.csv')
data

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [107]:
feature=data.groupby('class').mean()
feature

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

In [112]:
import json
feature.to_json('mushrooms_categorized.json',orient='index')
data = json.load(open('mushrooms_categorized.json'))
data

{'0': {'cap-shape': 3.2661596958,
  'cap-surface': 1.6159695817,
  'cap-color': 4.5817490494,
  'bruises': 0.6539923954,
  'odor': 4.3346007605,
  'gill-attachment': 0.9543726236,
  'gill-spacing': 0.2851711027,
  'gill-size': 0.0684410646,
  'gill-color': 6.6226235741,
  'stalk-shape': 0.6159695817,
  'stalk-root': 1.4980988593,
  'stalk-surface-above-ring': 1.7756653992,
  'stalk-surface-below-ring': 1.7984790875,
  'stalk-color-above-ring': 6.0988593156,
  'stalk-color-below-ring': 6.0646387833,
  'veil-type': 0.0,
  'veil-color': 1.9315589354,
  'ring-number': 1.1254752852,
  'ring-type': 3.0076045627,
  'spore-print-color': 3.2015209125,
  'population': 3.283269962,
  'habitat': 1.1482889734},
 '1': {'cap-shape': 3.4361593463,
  'cap-surface': 2.0551583248,
  'cap-color': 4.4218590398,
  'bruises': 0.1593462717,
  'odor': 3.9407558733,
  'gill-attachment': 0.9954034729,
  'gill-spacing': 0.0286006129,
  'gill-size': 0.5679264556,
  'gill-color': 2.8636363636,
  'stalk-shape': 0.51

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3