In [1]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Total Mean

In [2]:
num = 0
den = 0
for i in range(len(m)):
    for j in m[i]:
        num += j
        den += 1
mean = num/den
print("Total mean =", mean)      

Total mean = 5.5


## Row Mean

In [3]:
for i in range(len(m)):
    num = 0
    den = 0
    for j in m[i]:
        num += j
        den += 1
    mean = num/den
    print("Row", i,", mean =", mean)
                

Row 0 , mean = 1.5
Row 1 , mean = 5.5
Row 2 , mean = 9.5


## Column Mean

In [4]:
for i in range(4):
    col = m[:,i]
    num = 0
    den = 0
    for j in col:
        num += j
        den += 1
    mean = num/den
    print("Column", i, ", mean =", mean)

Column 0 , mean = 4.0
Column 1 , mean = 5.0
Column 2 , mean = 6.0
Column 3 , mean = 7.0
