In [43]:
import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print(u)
print(v)

[1 3 5 7]
[2 4 6 8]


## Outer product using outer function

In [8]:
print(np.outer(u,v))

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


## Outer product using nested for loop

In [46]:
for i in u:
    row = []
    for j in v:
        row.append(i*j)
    print(row)

[2, 4, 6, 8]
[6, 12, 18, 24]
[10, 20, 30, 40]
[14, 28, 42, 56]
