In [42]:
import pandas as pd
import numpy as np
import json
import csv

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [119]:
#LIST
list1=[i for i in range(10)]
out_file_name = "data_int.txt"
with open(out_file_name, 'a') as outfile:
    outfile.write(str(list1)+ '\n')
!cat data_int.txt
#MATRIX
mat = np.ones((5, 5))
with open(out_file_name, 'a') as outfile:
        outfile.write(str(mat)+ '\n')
!cat data_int.txt

import csv
# CONVERT TO CVS
file_name = "data_int.txt"





[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [120]:
#!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
data1 = json.load(open('user_data.json'))
df = pd.json_normalize(data1)
df=df[df["CreditCardType"]=="American Express"]
df.to_csv("user_data.csv")
print(len(df))

20


3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [70]:
#!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
    
file_name= "mushrooms_categorized.csv"
data = pd.read_csv(file_name)
dataCLA0=data[data["class"]==0]
dataCLA1=data[data["class"]==1]

list1=['cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']
## CLASS 0
print("CLASS 0")
for i in list1:
    data_0=np.mean(dataCLA0.groupby([i]).size())
    print(i,data_0)  
## CLASS 1
print("CLASS 1")
for i in list1:
    data_1=np.mean(dataCLA1.groupby([i]).size())
    print(i,data_1)  
    
    
#CONVERT TO JSON
data.to_json("mushrooms_categorized.json", orient = "records")

CLASS 0
cap-shape 841.6
cap-surface 1402.6666666666667
cap-color 420.8
bruises 2104.0
odor 1402.6666666666667
gill-attachment 2104.0
gill-spacing 2104.0
gill-size 2104.0
gill-color 420.8
stalk-shape 2104.0
stalk-root 841.6
stalk-surface-above-ring 1052.0
stalk-surface-below-ring 1052.0
stalk-color-above-ring 701.3333333333334
stalk-color-below-ring 701.3333333333334
veil-type 4208.0
veil-color 1402.6666666666667
ring-number 2104.0
ring-type 1402.6666666666667
spore-print-color 526.0
population 701.3333333333334
habitat 601.1428571428571
CLASS 1
cap-shape 783.2
cap-surface 979.0
cap-color 489.5
bruises 1958.0
odor 559.4285714285714
gill-attachment 1958.0
gill-spacing 1958.0
gill-size 1958.0
gill-color 391.6
stalk-shape 1958.0
stalk-root 979.0
stalk-surface-above-ring 979.0
stalk-surface-below-ring 979.0
stalk-color-above-ring 652.6666666666666
stalk-color-below-ring 652.6666666666666
veil-type 3916.0
veil-color 1958.0
ring-number 1305.3333333333333
ring-type 979.0
spore-print-color 783.

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [113]:
#!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
       
ind=1
dig_len=6
with open('credit_card.dat','rb') as file:        
    for line in file:
        if ind==51:break
        dig1=int(line[dig_len*0:dig_len*1],2)
        dig2=int(line[dig_len*1:dig_len*2],2)
        dig3=int(line[dig_len*2:dig_len*3],2)
        dig4=int(line[dig_len*3:dig_len*4],2)
        dig5=" "
        dig11=int(line[dig_len*5:dig_len*6],2)
        dig21=int(line[dig_len*6:dig_len*7],2)
        dig31=int(line[dig_len*7:dig_len*8],2)
        dig41=int(line[dig_len*8:dig_len*9],2)
        dig51=" "
        dig12=int(line[dig_len*10:dig_len*11],2)
        dig22=int(line[dig_len*11:dig_len*12],2)
        dig32=int(line[dig_len*12:dig_len*13],2)
        dig42=int(line[dig_len*13:dig_len*14],2)
        dig52=" "
        dig13=int(line[dig_len*15:dig_len*16],2)
        dig23=int(line[dig_len*16:dig_len*17],2)
        dig33=int(line[dig_len*17:dig_len*18],2)
        dig43=int(line[dig_len*18:dig_len*19],2)
        dig53=" "
        print("credit card",ind," code number is:",
              dig1,dig2,dig3,dig4,dig5,
              dig11,dig21,dig31,dig41,dig51,
              dig12,dig22,dig32,dig42,dig52,
              dig13,dig23,dig33,dig43,dig53)
        ind+=1

credit card 1  code number is: 55 54 52 56   53 54 55 51   51 55 55 53   50 50 55 49  
credit card 2  code number is: 51 50 53 55   56 50 52 55   51 51 53 52   50 50 54 54  
credit card 3  code number is: 50 55 50 50   48 48 48 49   52 48 49 49   54 54 53 50  
credit card 4  code number is: 48 54 54 49   51 48 54 51   51 55 52 50   51 49 53 48  
credit card 5  code number is: 48 52 51 50   49 54 48 56   49 52 54 50   52 55 52 50  
credit card 6  code number is: 53 56 50 55   50 48 50 55   56 55 56 53   55 51 48 51  
credit card 7  code number is: 53 55 55 52   56 53 50 56   50 48 56 55   49 49 49 55  
credit card 8  code number is: 56 49 52 48   49 50 49 48   54 51 53 50   50 56 52 53  
credit card 9  code number is: 53 55 54 52   49 49 51 51   55 51 48 49   55 49 48 48  
credit card 10  code number is: 54 52 53 54   49 55 51 55   52 49 50 54   54 55 50 54  
credit card 11  code number is: 49 50 50 56   56 54 51 49   55 51 56 50   48 48 48 48  
credit card 12  code number is: 55 48 53 

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3