In [1]:
import pandas as pd
import numpy as np

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [3]:
#NOTE: I am using Windows so the command that I am using is "type" and not the "cat"

#Creating Data Integers
import numpy as np
import pandas as pd

my_list = np.array(range(10))
print("List of integers in range of 10 : \n", my_list)

#converting to txt
open_txt = open('data_integer.txt','w')
open_txt.write(str(my_list))
open_txt.close

print("\nOpened Data Integers from txt file: ")
!type data_integer.txt

#Creating Matrix of 5x5 floats
data_float = np.array(range(25)).reshape(5,5)
print("\nFloats of 25 in 5x5: \n", data_float)

#converting to txt
open_matrix = open('data_float.txt','w')
open_matrix.write(str(data_float))
open_matrix.close()

print("\nOpened Floats from txt file: ")
!type data_float.txt

#load the txt file of the previous point
filename = 'D:/Projects/HighLevelProgramming2021/data_float.txt'

#convert it to a csv file by hand
with open('data_integer.txt') as data_integer_csv:
    print("\nData in CSV: \n", data_integer_csv.read())
read_file = pd.read_csv ('D:/Projects/HighLevelProgramming2021/data_integer.txt')
read_file.to_csv ('D:/Projects/HighLevelProgramming2021/data_integer.csv', index=None)
    

List of integers in range of 10 : 
 [0 1 2 3 4 5 6 7 8 9]

Opened Data Integers from txt file: 
[0 1 2 3 4 5 6 7 8 9]

Floats of 25 in 5x5: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Opened Floats from txt file: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Data in CSV: 
 [0 1 2 3 4 5 6 7 8 9]


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [4]:
import json, csv


user_data = json.load(open('data/user_data.json'))
with open('data/user_data.json') as f:
    data = json.load(f)
data = pd.DataFrame(user_data)
    
#filtering data by the "CreditCardType" when it equals to "American Express"
data = data[data['CreditCardType'] == 'American Express']
data.to_csv(r'D:/Projects/HighLevelProgramming2021/data/user_data.csv')
pd.read_csv(r'D:/Projects/HighLevelProgramming2021/data/user_data.csv')

Unnamed: 0   ID               JobTitle                       EmailAddress  \
0            1    2    Investment  Advisor       Clint_Thorpe5003@bulaffy.com   
1           11   12         Retail Trainee   Phillip_Carpenter9505@famism.biz   
2           27   28        Project Manager        Russel_Graves1378@extex.org   
3           38   39            Stockbroker       Leanne_Newton1268@typill.biz   
4           56   57         Budget Analyst          Tony_Giles1960@iatim.tech   
5           61   62           CNC Operator        Owen_Allcott5125@bauros.biz   
6           67   68        Project Manager           Liam_Lynn3280@kideod.biz   
7           73   74                Dentist      Regina_Woodcock5820@yahoo.com   
8           80   81          HR Specialist       Carter_Wallace9614@atink.com   
9           91   92    Staffing Consultant           Maia_Stark2797@jiman.org   
10          96   97            Stockbroker          Ciara_Lomax982@bauros.biz   
11         115  116    Staffing Consultant      Isabel_Ellwood1475@fuliss.net   
12         147  148           CNC Operator  Abdul_Townend2202@infotech44.tech   
13         149  150             Fabricator        Caleb_Poulton1735@atink.com   
14         150  151     Restaurant Manager         Ronald_Lewis6777@deavo.com   
15         153  154                Bellman        Faith_Seymour3829@twace.org   
16         168  169        Assistant Buyer      Anthony_Hancock9083@qater.org   
17         175  176  Healthcare Specialist    Isabella_Willson5478@nanoff.biz   
18         181  182             Pharmacist     Stephanie_Darcy3298@bauros.biz   
19         198  199    Investment  Advisor         Ryan_Kennedy5565@corti.com   

    FirstNameLastName           CreditCard    CreditCardType  
0        Clint Thorpe  7083-8766-0251-2345  American Express  
1   Phillip Carpenter  3657-0088-0820-5247  American Express  
2       Russel Graves  6718-4818-8011-6024  American Express  
3       Leanne Newton  5438-0816-4166-4847  American Express  
4          Tony Giles  8130-3425-7573-7745  American Express  
5        Owen Allcott  4156-0107-7210-2630  American Express  
6           Liam Lynn  7152-3247-6053-2233  American Express  
7     Regina Woodcock  0208-1753-3870-8002  American Express  
8      Carter Wallace  4256-7201-6717-4322  American Express  
9          Maia Stark  3851-1403-1734-6321  American Express  
10        Ciara Lomax  3702-3440-2472-5424  American Express  
11     Isabel Ellwood  3738-0882-0066-6683  American Express  
12      Abdul Townend  4224-1226-3557-3448  American Express  
13      Caleb Poulton  8203-6875-5225-0341  American Express  
14       Ronald Lewis  7212-0155-5014-8471  American Express  
15      Faith Seymour  4170-5186-6887-6558  American Express  
16    Anthony Hancock  0832-3357-6010-6550  American Express  
17   Isabella Willson  5177-4868-4623-0384  American Express  
18    Stephanie Darcy  0264-4020-5106-5576  American Express  
19       Ryan Kennedy  3166-6287-6242-7207  American Express

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [5]:
#Exploring and printing DataFrame

import pandas as pd
file = 'D:\Projects\HighLevelProgramming2021\data\mushrooms_categorized.csv'
dataframe = pd.read_csv(file)
print("DataFrame: \n", dataframe)
print("\nExploring data of 5 rows: \n", pd.read_csv(file, nrows=5, skiprows=range(1,1)))

#calculate, using groupby(), the average value of each feature, separately for each class
mean_value = dataframe.groupby(['class']).mean
print("\nAverage value of each feature: \n", mean_value())




DataFrame: 
       class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2    

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [6]:
new_data = pd.read_csv('data/credit_card.dat')

def convert(n):
    string = str()
    for i in range(0, len(str(n))-6, 6):
        character = chr(int(n[i:i+6], 2)) #taking the 6 bits for each character and converting the binary to decimal, then from decimal to char
        string+= character #adding the character to string
    return string

new_data[new_data.columns[0]] = new_data[new_data.columns[0]].apply(convert)

new_data.rename(columns = {'1101111101101101001110001000001101011101101101111100111000001100111101111101111101011000001100101100101101111100011010':'Credit Card Number'}, inplace = True)
new_data

Credit Card Number
0   3257 8247 3354 2266
1   2722 0001 4011 6652
2   0661 3063 3742 3150
3   0432 1608 1462 4742
4   5827 2027 8785 7303
5   5774 8528 2087 1117
6   8140 1210 6352 2845
7   5764 1133 7301 7100
8   6456 1737 4126 6726
9   1228 8631 7382 0000
10  7051 0160 5374 3166
11  0618 3587 1630 6376
12  1545 5454 7444 5636
13  6735 3116 3202 6834
14  7287 5011 1547 8413
15  7033 2607 3328 4200
16  2568 5244 1874 5024
17  1684 2253 7570 7118
18  0672 2576 0575 6631
19  6332 8353 8787 1340
20  1813 3361 1175 4211
21  2477 6450 8840 2368
22  5512 3505 2563 1326
23  3083 7882 0621 0025
24  4521 5148 8045 0334
25  7563 3654 8713 5787
26  8324 2664 0476 5561
27  0565 2504 7168 3510
28  5107 5507 1767 0738
29  2462 1821 2448 1443
30  2788 0638 6861 6554
31  5851 5873 5474 0547
32  0670 1004 4013 2655
33  5874 5506 3048 0806
34  2805 5401 8462 1260
35  5083 8406 6310 1862
36  1076 1445 3013 2266
37  8440 4804 4844 5277
38  4758 6141 0686 1387
39  7586 0675 0315 2568
40  2544 1258 7432 5165
41  3474 5023 4434 5626
42  1410 0270 0434 5086
43  7315 4446 1104 4215
44  0224 7742 8300 0266
45  0170 2700 3145 0640
46  2006 2437 8054 1600
47  8142 4055 1776 0026
48  3026 7380 1241 1084

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3