1. Perform the following operations on plain txt files:

 - create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the cat command to print the content of the file.
 - create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the cat command to print the content of the file.
 - load the txt file of the previous point and convert it to a csv file by hand.

In [2]:
import pandas as pd
import numpy as np

In [6]:
lst = [1,2,3,4,5]

with open("data_int.txt", 'w') as f:
    f.write(str(lst) + '\n')

#with open("file.txt", 'r') as f:
#    score = [line.rstrip('\n') for line in f]

!type data_int.txt

[1, 2, 3, 4, 5]


In [10]:
arr = np.arange(25).reshape(5,5)

with open("data_float.txt", 'w') as f:
    f.write(str(arr) + '\n')
    
!type data_float.txt

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
read_file = pd.read_csv ('data_float.txt')
read_file.to_csv ('data_float.csv', index=None)

2. Load the file user_data.json, which can be found at:

https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [50]:
import json
user_data = json.load(open('user_data.json'))

#filtering loaded data
AmericanExpress =[i for i in user_data if i["CreditCardType"] == "American Express"]
AE_data = pd.read_json(json.dumps(AmericanExpress))
AE_data.to_csv('user_data.csv', index=False)

!type user_data.csv

ID,JobTitle,EmailAddress,FirstNameLastName,CreditCard,CreditCardType
2,Investment  Advisor,Clint_Thorpe5003@bulaffy.com,Clint Thorpe,7083-8766-0251-2345,American Express
12,Retail Trainee,Phillip_Carpenter9505@famism.biz,Phillip Carpenter,3657-0088-0820-5247,American Express
28,Project Manager,Russel_Graves1378@extex.org,Russel Graves,6718-4818-8011-6024,American Express
39,Stockbroker,Leanne_Newton1268@typill.biz,Leanne Newton,5438-0816-4166-4847,American Express
57,Budget Analyst,Tony_Giles1960@iatim.tech,Tony Giles,8130-3425-7573-7745,American Express
62,CNC Operator,Owen_Allcott5125@bauros.biz,Owen Allcott,4156-0107-7210-2630,American Express
68,Project Manager,Liam_Lynn3280@kideod.biz,Liam Lynn,7152-3247-6053-2233,American Express
74,Dentist,Regina_Woodcock5820@yahoo.com,Regina Woodcock,0208-1753-3870-8002,American Express
81,HR Specialist,Carter_Wallace9614@atink.com,Carter Wallace,4256-7201-6717-4322,American Express
92,Staffing Consultant,Maia_Stark2797@jiman.org,Maia Stark,385

3. Load the file from this url:

https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv with Pandas.

 - explore and print the DataFrame
 - calculate, using groupby(), the average value of each feature, separately for each class
 - save the file in a JSON format.

In [5]:
import pandas as pd
mushrooms_data = pd.read_csv("mushrooms_categorized.csv")
mushrooms_data.iloc[:]

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [6]:
mushrooms_mean = mushrooms_data.groupby('class').mean()
mushrooms_mean

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

In [8]:
import json

mushrooms_mean.to_json("mushrooms_mean.json")
!type mushrooms_mean.json


{"cap-shape":{"0":3.2661596958,"1":3.4361593463},"cap-surface":{"0":1.6159695817,"1":2.0551583248},"cap-color":{"0":4.5817490494,"1":4.4218590398},"bruises":{"0":0.6539923954,"1":0.1593462717},"odor":{"0":4.3346007605,"1":3.9407558733},"gill-attachment":{"0":0.9543726236,"1":0.9954034729},"gill-spacing":{"0":0.2851711027,"1":0.0286006129},"gill-size":{"0":0.0684410646,"1":0.5679264556},"gill-color":{"0":6.6226235741,"1":2.8636363636},"stalk-shape":{"0":0.6159695817,"1":0.5148110317},"stalk-root":{"0":1.4980988593,"1":0.6925434116},"stalk-surface-above-ring":{"0":1.7756653992,"1":1.3595505618},"stalk-surface-below-ring":{"0":1.7984790875,"1":1.3942798774},"stalk-color-above-ring":{"0":6.0988593156,"1":5.5127681307},"stalk-color-below-ring":{"0":6.0646387833,"1":5.5045965271},"veil-type":{"0":0.0,"1":0.0},"veil-color":{"0":1.9315589354,"1":2.0020429009},"ring-number":{"0":1.1254752852,"1":1.0091930541},"ring-type":{"0":3.0076045627,"1":1.5229826353},"spore-print-color":{"0":3.2015209125,

4. Get the binary file named credit_card.dat from this address:

https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat
and convert the data into the real credit card number, knowing that:

 - each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
 - each character is written using a 6 bit binary representation (including the whitespace)
 - the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored
 

Hint: convert the binary numbers to the decimal representation first, and then use the chr() function to convert the latter to a char

In [51]:
with open('credit_card.dat','rb') as read_dat: 
    line = read_dat.readlines() # read the lines
    for row in line:
        if(len(row) > 5):
            utf_2_strng = row.decode("utf-8")  #decode the line into string\n",
            utf_2_strng = utf_2_strng[0:114]
            start_digit = 0
            digit_space = 6
            card_digits=[]
            
            for i in range(19):
                end_digit = start_digit + digit_space
                digits_4 = utf_2_strng[start_digit:(start_digit + digit_space)]
                card_digits.append(digits_4)
                start_digit = start_digit + digit_space
                credit_card = '/'
                counter = 1
                
            for i in range(0,19):
                credit_card = credit_card + chr(int(card_digits[i],2))
            print("Number of the Credit Card is :", credit_card)

Number of the Credit Card is : /7648 5673 3775 2271
Number of the Credit Card is : /3257 8247 3354 2266
Number of the Credit Card is : /2722 0001 4011 6652
Number of the Credit Card is : /0661 3063 3742 3150
Number of the Credit Card is : /0432 1608 1462 4742
Number of the Credit Card is : /5827 2027 8785 7303
Number of the Credit Card is : /5774 8528 2087 1117
Number of the Credit Card is : /8140 1210 6352 2845
Number of the Credit Card is : /5764 1133 7301 7100
Number of the Credit Card is : /6456 1737 4126 6726
Number of the Credit Card is : /1228 8631 7382 0000
Number of the Credit Card is : /7051 0160 5374 3166
Number of the Credit Card is : /0618 3587 1630 6376
Number of the Credit Card is : /1545 5454 7444 5636
Number of the Credit Card is : /6735 3116 3202 6834
Number of the Credit Card is : /7287 5011 1547 8413
Number of the Credit Card is : /7033 2607 3328 4200
Number of the Credit Card is : /2568 5244 1874 5024
Number of the Credit Card is : /1684 2253 7570 7118
Number of th