In [34]:
x=[x for x in range(100)]
b=[]
for j in range (1,101):
    if j%3==0 and j%5==0:
        b.insert(j,"HelloWorld")
        print("HelloWorld")
    elif j%5==0:
        b.insert(j,"World")
        print("World")
    elif j%3==0:
        b.insert(j,"Hello")
        print("Hello")
    else:
        print(j)

c=[]
for z in range(1,100):
    if b[z]=="helloworld":
        c.append("pythonworks")
    elif b[z]=="hello":
        c.append("python")
    elif b[z]=="world":
        c.append("works")
    else:
        c.append(z)
t=tuple(c)
print(t)

1
2
Hello
4
World
Hello
7
8
Hello
World
11
Hello
13
14
HelloWorld
16
17
Hello
19
World
Hello
22
23
Hello
World
26
Hello
28
29
HelloWorld
31
32
Hello
34
World
Hello
37
38
Hello
World
41
Hello
43
44
HelloWorld
46
47
Hello
49
World
Hello
52
53
Hello
World
56
Hello
58
59
HelloWorld
61
62
Hello
64
World
Hello
67
68
Hello
World
71
Hello
73
74
HelloWorld
76
77
Hello
79
World
Hello
82
83
Hello
World
86
Hello
88
89
HelloWorld
91
92
Hello
94
World
Hello
97
98
Hello
World


IndexError: list index out of range

x=input("enter your first value")
b=input("Enter 2nd value")
print(x,b)
b=3
c=4
print(c+b)
type(x)
type(c)


Function Declaration

IndexError: list index out of range

Function and without global variable

In [16]:
t=input("Enter a Word that you like")
r=[m for m in t ]
print(r)

#a=input("Enter First Character")[0]

#y="a"
i=0
v=len(r)-2
o=v
while i<v:
    y=input("Enter Character")[0]
    if(y in r):
        print("letter match")
    else:
        print("try again")
    i+=1
    o-=1
    if(o==0):
        print("You have 0 testing left")
    else:
        print("You have ",+o ,"testing left")
  

Enter a Word that you likejawad asif
['j', 'a', 'w', 'a', 'd', ' ', 'a', 's', 'i', 'f']
Enter Characterj
letter match
You have  7 testing left
Enter Characterd
letter match
You have  6 testing left
Enter Characterf
letter match
You have  5 testing left
Enter Characterd
letter match
You have  4 testing left
Enter Characters
letter match
You have  3 testing left
Enter Charactera
letter match
You have  2 testing left
Enter Characters
letter match
You have  1 testing left
Enter Characterd
letter match
You have 0 testing left


In [2]:
  if(o==0):
        print("You have 0 testing left")
    else:
        print("You have ",+o ,"testing left")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [13]:
def conversion(x):
    b=bin(x)
    print("The Binary representation of the ",x, "is = ",b)
    h=hex(x)
    print("The Binary representation of the ",x, "is = ",h)
    
    print("Converting Back to Binary and Hexadecimal")
    d=int(b,2)
    print("The Decimal Representation is",d)
    print("The Hexa Decimal Representation is", int(h,16))

    
conversion(2)

The Binary representation of the  2 is =  0b10
The Binary representation of the  2 is =  0x2
Converting Back to Binary and Hexadecimal
The Decimal Representation is 2
The Hexa Decimal Representation is 2


In [1]:
import numpy as np
# float_epsilon = np.finfo(float).eps
# print(float_epsilon)


def quadratic(a,b,c):
    
        re=(a*c)/(-b-(np.sqrt((b**2)-(a*c))))
        re1=(a*c)/(-b-(np.sqrt((b**2)+(a*c))))

        x1=(-b+(np.sqrt((b**2)-(4*a*c))))/2*a
        x2=(-b-(np.sqrt((b**2)-(4*a*c))))/2*a
        
        print("The resutl for Positive (+) is {} and for Negative (-) is {}".format(x1,x2))
        print(re)
        print(re1)
   
quadratic(1,6,5)


# def quadratic1(a,b,c):
#         x1=(-b+(np.sqrt((b**2)-(4*a*c))))
#         x2=(-b-(np.sqrt((b**2)-(4*a*c))))
        
#         print("The resutl for Positive (+) is {} and for Negative (-) is {}".format(x1,x2))
        
    
# quadratic1(0.001,1000,0.001)
    


The resutl for Positive (+) is -1.0 and for Negative (-) is -5.0
-0.43223563716997804
-0.4031242374328487


In [6]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)
print(np.mean(m))
print(np.mean(m,axis=0))
print(np.mean(m,axis=1))





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]
