1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [13]:
import math 

b = 5./15.
f = 2*math.atan(b)
print("angolo phi",f)

cr = 1 -  math.cos(f)
print("angolo solido rivelato", 2*math.pi*cr)

perso = 2*math.pi/3 + math.pi/6 - 3*f/2

cp = 1 - math.cos(perso)
print("angolo solido perso ",2*math.pi*cp)

angtot = 2*math.pi*(cp+cr)

print("angolo solido totale", angtot)

print("percentuale rivelata", cr/(cp+cr))

angolo phi 0.6435011087932844
angolo solido rivelato 1.256637061435917
angolo solido perso  6.797490451227155
angolo solido totale 8.054127512663072
percentuale rivelata 0.1560239839088932


In [3]:
import numpy as np 

m = np.arange(12).reshape((3,4))

print(m)
print("total mean:",'\n', m.mean())
print("mean of each row:", '\n', np.mean(m,1))
print("mean of each coloumn:", '\n', np.mean(m,0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
total mean: 
 5.5
mean of each row: 
 [1.5 5.5 9.5]
mean of each coloumn: 
 [4. 5. 6. 7.]


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [20]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8]) 

# 1)outer function
p_1 = np.outer(u,v)
print("The outer product of u and v computed with outer function is ", '\n', p_1)

#2)for loop
#Devo fare prodotto di un elemento di v per tutti gli elementi di v su tutti quelli di u 
#devo quindi ciclare su u e su v e il risultato lo appendo in un array di np

#????
p_2 = np.array([ (i*j,i*j) for i in range(u) for j in range (v)])


#3)broadcasting operations
#non credo sia la cosa giusta da fare
v_col = v.reshape((4,1))
print(v_col)
p_3 = u * v_col 
print("the outer product of u and v computed with broadcasting operators is", '\n', p_3)


The outer product of u and v computed with outer function is  
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


TypeError: only integer scalar arrays can be converted to a scalar index

3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [22]:
#devo usare np.arange() on 10 colonne e 6 righe equispaziate da 0.1
m = np.array([np.arange(0.,1.,0.1)],[np.arange(1.,2.,0.1)]) 
print(m)

TypeError: data type not understood

4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)