In [28]:
import pandas as pd
import numpy as np
import json
import csv

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [18]:

#creating a list of integer numbers
l = [1, 2, 3, 4, 5]
#defining txt file name
file1 = "data_int.txt"
#creating and saving the file 
with open(file1, 'w') as f1:
    for i in l:
        f1.write(str(i) + '\n')
#printing the content
!cat data_int.txt

#creating a matrix 5x5
for j in range(6): 
    m = np.array([np.arange(0,j,0.2)])
M = m.reshape(5,5)
#creating and saving the file
file2 = "data_float.txt"
with open(file2, 'w') as f2:
    for i in M:
        f2.write(str(i) + '\n')
#printing the content
!cat data_float.txt

#loading data_float.txt
read_file = pd.read_csv ("data_float.txt")
#converting into cvs file
read_file.to_csv ("data_float.csv", index=None)

1
2
3
4
5
[0.  0.2 0.4 0.6 0.8]
[1.  1.2 1.4 1.6 1.8]
[2.  2.2 2.4 2.6 2.8]
[3.  3.2 3.4 3.6 3.8]
[4.  4.2 4.4 4.6 4.8]


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [30]:

#downloading the file (only once then I can comment this line to avoid downloading the file several times)
#!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json -P /
#loading the file
j_data = json.load(open('user_data.json'))

#filtering by CreditCardType 
j_filtred = [x for x in j_data if x['CreditCardType'] == 'American Express']

#creating a new json file for the filtred data
with open('f_json.json', 'w') as outfile:
   json.dump(j_filtred, outfile)
#checking if the file is right printing it with !cat
!cat f_json.json

df = pd.read_json('f_json.json')
df.to_csv ('f_csv.csv', index = None)

[{"ID": "2", "JobTitle": "Investment  Advisor", "EmailAddress": "Clint_Thorpe5003@bulaffy.com", "FirstNameLastName": "Clint Thorpe", "CreditCard": "7083-8766-0251-2345", "CreditCardType": "American Express"}, {"ID": "12", "JobTitle": "Retail Trainee", "EmailAddress": "Phillip_Carpenter9505@famism.biz", "FirstNameLastName": "Phillip Carpenter", "CreditCard": "3657-0088-0820-5247", "CreditCardType": "American Express"}, {"ID": "28", "JobTitle": "Project Manager", "EmailAddress": "Russel_Graves1378@extex.org", "FirstNameLastName": "Russel Graves", "CreditCard": "6718-4818-8011-6024", "CreditCardType": "American Express"}, {"ID": "39", "JobTitle": "Stockbroker", "EmailAddress": "Leanne_Newton1268@typill.biz", "FirstNameLastName": "Leanne Newton", "CreditCard": "5438-0816-4166-4847", "CreditCardType": "American Express"}, {"ID": "57", "JobTitle": "Budget Analyst", "EmailAddress": "Tony_Giles1960@iatim.tech", "FirstNameLastName": "Tony Giles", "CreditCard": "8130-3425-7573-7745", "CreditCard

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [50]:
#downloading the file (only once then I can comment this line to avoid downloading the file several times)
#!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv -P /

f = "mushrooms_categorized.csv"
#loading the file with pandas
f_pandas = pd.read_csv(f)
#f_pandas

#getting the columns of my dataframe
cols = f_pandas.columns
print(cols)

#calculating the average value of each column so each feature and turned into a list 
f_pandas.groupby('class')[cols].mean()
print(average)

json_f = f_pandas.groupby('class')[cols].mean().to_json(orient='index')
#creating a json file
json_file = 'average.json'
#storing in it averages of features for each class
with open('average.json', 'w') as outfile:
    json.dump(json_f, outfile)

!cat average.json

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')
       class  cap-shape  cap-surface  cap-color   bruises      odor  \
class                                                                 
0        0.0   3.266160     1.615970   4.581749  0.653992  4.334601   
1        1.0   3.436159     2.055158   4.421859  0.159346  3.940756   

       gill-attachment  gill-spacing  gill-size  gill-color  ...  \
class                                                        ...   
0             0.954373      0.285171   0.068441    6.622624  ...   
1             0.995403      0.028601   0.567926    2.863636  ...   

       s

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [ ]:
!wget 

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3