In [63]:
import pandas as pd
import numpy as np

# csv files handling
import csv

# json files handling
import json

In [10]:
# define path for saving output files
path = "outputData/"

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [21]:
# list of integers
l = [i for i in range(10)]

# define file name
outFile = path + "data_int.txt"

# write to file
with open(outFile, 'w') as outfile:
    for i in l:
        outfile.write(str(i) + '\n')

# cat file
!cat outputData/data_int.txt

0
1
2
3
4
5
6
7
8
9


In [22]:
# random matrix of floats
m = np.random.uniform(low=0., high=10., size=(5,5))

# define file name
outFile = path + "data_float.txt"

# write to file
with open(outFile, 'w') as ofile:
    for i in m:
        ofile.write(str(i) + '\n')

# cat file
!cat outputData/data_float.txt

[5.13739696 8.56857424 2.00352189 2.33757955 9.33999177]
[0.12241522 8.62759695 1.04730244 7.68493855 7.66183312]
[0.67990285 9.22928556 4.57343804 7.31478408 1.682582  ]
[5.34132583 4.64380584 5.44168565 4.60928054 6.64442607]
[1.44547663 7.94348953 6.24048448 7.90490188 2.7318633 ]


In [62]:
# define file name
outFile2 = path + "data_float.csv"

with open(outFile, 'r') as ifile:
    with open(outFile2, 'w') as ofile:  
        
        # get lines from input file
        for l in ifile:
            
            # replace square brackets
            l = l.replace('[', '').replace(']', '')
            
            # strip each line and then split into a tuple
            line = (l.strip().split(' '))
            
            # write to csv using the csv.writer method
            writer = csv.writer(ofile)
            writer.writerow(line)
            
# cat file
!cat outputData/data_float.csv

2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [66]:
# get data
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json -P data/

--2021-11-22 13:51:12--  https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
Resolving www.dropbox.com (www.dropbox.com)... 162.125.69.18, 2620:100:6025:18::a27d:4512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.69.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/sz5klcdpckc39hd/user_data.json [following]
--2021-11-22 13:51:16--  https://www.dropbox.com/s/raw/sz5klcdpckc39hd/user_data.json
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc4bd142a4086a27744c9dea24f5.dl.dropboxusercontent.com/cd/0/inline/BacbrejxTzz6Nr-mA8cCE_24WcF1sP_VmdGj4hWXNQNHx630xo5E4j80DX53gowHJxTtmgtJ_7ZYIoRsEy9rx1rf6_kF00OHwvEiziLpTbC9rrH-R6s3GRnmV6TuFjQV0Eyb50ifwWXOuL2UkrIqrT1O/file# [following]
--2021-11-22 13:51:17--  https://uc4bd142a4086a27744c9dea24f5.dl.dropboxusercontent.com/cd/0/inline/BacbrejxTzz6Nr-mA8cCE_24WcF1sP_VmdGj4hWXNQNHx630xo5E4j80DX53gowHJxTtmgtJ_7ZYIoRsE

In [72]:
# get file
filename = "data/user_data.json"
data = json.load(open(filename))
#!cat data/user_data.json

'''
    TO DO
'''

3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3