In [1]:
#importing libraries
import pandas as pd
import numpy as np

1\. Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named "data_int.txt". Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named "data_float.txt". Use the `cat` command to print the content of the file.
+ load the txt file of the previous point and convert it to a csv file by hand.

In [18]:
#1)


file_name = 'data/data_int.txt'
list_integers = [1,2,3,4,5]
string_ints = [str(int_)+' ' for int_ in list_integers]
str1 = " "

for i in string_ints:
    str1 += i

with open(file_name, 'a') as outfile:
    outfile.write(str1)
    
print("First file: the array of integers\n")
!cat data/data_int.txt




First file: the array of integers

 1 2 3 4 5  1 2 3 4 5  1 2 3 4 5 

In [19]:
#2)

file_name2 = 'data/data_float.txt'
matrix = np.zeros((5,5))
matrix += np.arange(5)

with open(file_name2, 'a') as outfile:
    outfile.write(str(matrix))

print("\nSecond file: the matrix \n")
!cat data/data_float.txt


Second file: the matrix 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [22]:
#3) txt to csv by hand
with open('data/data_float.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('csv_conversion.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        #writer.writerow(('title', 'intro'))
        writer.writerows(lines)

In [20]:
#3) txt to csv smart way
import csv

read_file = pd.read_csv (r'data/data_float.txt')
read_file.to_csv (r'Csv_conversion.csv', index=None)


2\. Load the file *user_data.json*, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [39]:
import json
data = json.load(open('user_data.json'))
out_file = open('csv_file', 'w')
writer = csv.writer(out_file)

#data = pd.read_csv(file_name, nrows=1000, names=['CreditCardType', 'American Express'])
#print(data)

#filtered_data = list(filter(lambda x: x['CreditCardType'] == 'American Express', data))
#print(filtered_data)
filtered_data= []
for x in data:
    if (x['CreditCardType']  == 'American Express' ):
        filtered_data.append(x)
        writer.writerow(x)
        
out_file.close()



3\. Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [53]:
#printing data frame

file_name = "mushrooms_categorized.csv"
data = pd.read_csv(file_name)
data
#with open('file_json.json', )

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [54]:
output_data= data.groupby('class').mean()
output_data

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

4\. Get the binary file named *credit_card.dat* from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [72]:
file_name = "credit_card.dat"

with open(file_name, mode = 'r') as f:
    for line in f:
        # print line by line
        #print(line)
        subline = line[:4]
        b = int(subline)
        b = int(b)
        print("b = ", b)

b =  1101
b =  1100
b =  1100
b =  1100
b =  1100
b =  1101
b =  1101
b =  1110
b =  1101
b =  1101
b =  1100
b =  1101
b =  1100
b =  1100
b =  1101
b =  1101
b =  1101
b =  1100
b =  1100
b =  1100
b =  1101
b =  1100
b =  1100
b =  1101
b =  1100
b =  1101
b =  1101
b =  1110
b =  1100
b =  1101
b =  1100
b =  1100
b =  1101
b =  1100
b =  1101
b =  1100
b =  1101
b =  1100
b =  1110
b =  1101
b =  1101
b =  1100
b =  1100
b =  1100
b =  1101
b =  1100
b =  1100
b =  1100
b =  1110
b =  1100
b =  1010


5\. **Optional**: load the remote file:

- https://www.dropbox.com/s/aamg1apjhclecka/regression_generated.csv

with Pandas and create a scatter plot with all possible combinations of the following features:
    
  + features_1
  + features_2
  + features_3